{% set name = "priori" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ohsu-comp-bio/regulon-enrichment/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 45694d7785857cc461f71dc409d68e818ce49f495bc4eea395bd6b5e53bfae40 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - priori = priori.priori:main

requirements:
  host:
    - python >=3.11.5
    - pip
    - setuptools

  run:
    - python >=3.11.5
    - dill >=0.3.1.1
    - numpy >=1.17.3
    - pandas >=0.25.3
    - scikit-learn >=0.21.3
    - scipy >=1.5.2
    - tqdm >=4.38.0
    - statsmodels >=0.12.2

test:
  commands:
    - priori --help

about:
  home: https://github.com/ohsu-comp-bio/regulon-enrichment
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Priori predicts transcription factor activity from RNA sequencing data using prior, literature-supported regulatory relationship information

extra:
  recipe-maintainers:
    - yasharw
